In [1]:
import pandas as pd

In [2]:
data = {
    'A': [1, 2, None, 4, 5],
    'B': [None, 2, 3, 4, 5],
    'C': [1, 2, 3, None, 5]
}
df = pd.DataFrame(data)

In [3]:
# Dropping rows

df_dropna = df.dropna()
print("After dropping rows with missing values:\n", df_dropna)

After dropping rows with missing values:
      A    B    C
1  2.0  2.0  2.0
4  5.0  5.0  5.0

In [5]:
data_2 = {
    'A': [1, 2, None, 4, 5],
    'B': [None, 2, 3, 4, 5],
    'C': [1, 2, 3, None, 5]
}
df_2 = pd.DataFrame(data)

In [6]:
# Replacing with mean/median/mode
df_mean = df_2.fillna(df_2.mean())
print("After replacing missing values with mean:\n", df_mean)

df_median = df_2.fillna(df_2.median())
print("After replacing missing values with median:\n", df_median)

df_mode = df_2.fillna(df_2.mode().iloc[0])
print("After replacing missing values with mode:\n", df_mode)

After replacing missing values with mean:
      A    B     C
0  1.0  3.5  1.00
1  2.0  2.0  2.00
2  3.0  3.0  3.00
3  4.0  4.0  2.75
4  5.0  5.0  5.00
After replacing missing values with median:
      A    B    C
0  1.0  3.5  1.0
1  2.0  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  2.5
4  5.0  5.0  5.0
After replacing missing values with mode:
      A    B    C
0  1.0  2.0  1.0
1  2.0  2.0  2.0
2  1.0  3.0  3.0
3  4.0  4.0  1.0
4  5.0  5.0  5.0